db:
   image: mongo:latest
   volumes:
     - ./data/runtime/db:/data/db
     - ./data/dump:/dump
   command: mongod --smallfiles

rocketchat:
   image: rocketchat/rocket.chat:latest
   environment:
     - MONGO_URL=mongodb://db:27017/rocketchat
     - ROOT_URL=http://<TYPE_HOST_IP_ADDRESS>
     - Accounts_UseDNSDomainCheck=false
     - HTTP_PROXY=http://solidproxy.exa-corp.co.jp:8080/
     - HTTPS_PROXY=http://solidproxy.exa-corp.co.jp:8080/
     - NO_PROXY=localhost,*.exa-corp.co.jp,127.0.0.1,172.*,160.14.*,10.*
   dns:
     - 160.14.95.11
     - 160.14.23.11
     - 160.14.254.1
   dns_search: exa-corp.co.jp
   links:
     - db:db
   ports:
     - 3000:3000

hubot:
    image: rocketchat/hubot-rocketchat:latest
    volumes:
    - ./data/hubot:/var/www/hubotscripts
    environment:
    - ROCKETCHAT_URL=<TYPE_HOST_IP_ADDRESS>:3000
    - ROCKETCHAT_ROOM=hubot
    - ROCKETCHAT_USER=rocketchatbot
    - ROCKETCHAT_PASSWORD=admin123
    - BOT_NAME=rocketchatbot
    - _EXTERNALSCRIPTS=hubot-diagnostics,hubot-help,hubot-seen,hubot-links,hubot-greetings
    links:
    - rocketchat:rocketchat
